// <auto-generated />
namespace TourismWebsiteAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IAMDUMBTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IAMDUMBTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202601170636488_IAMDUMBTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
